#!/usr/bin/env python

import os
import subprocess
import sys

USAGE = """\
Required environment variables:
\tBOSH_ENVIRONMENT
\tBOSH_DEPLOYMENT
Usage:
\tmedic <deployment_type>
For Example,
\tmedic scalablesyslog
\tmedic loggregator
\
"""

loggregator_vm_types=["doppler", "log-api", "reverse_log_proxy"]
scalable_syslog_vm_types=["adapter", "scheduler"]

def run_command(vm):
    bosh_cmd = subprocess.Popen([
        "bosh",
        "-e", os.environ['BOSH_ENVIRONMENT'],
        "-d", os.environ['BOSH_DEPLOYMENT'],
        "ssh", vm,
        "-c", "curl localhost:8080/health; echo;"
        ], stdout=subprocess.PIPE)
    bosh_cmd.wait()
    bosh_cmd_out = bosh_cmd.stdout

    for line in bosh_cmd_out:
        if line.find("stdout") == -1:
            continue
        parts = line.split(" ")
        print "{} {}".format(parts[0].strip(), parts[3].strip())

def main():
    deployment = parse_args()
    if deployment == "scalablesyslog":
        for vm in scalable_syslog_vm_types:
            run_command(vm)
    elif deployment == "loggregator":
        for vm in loggregator_vm_types:
            run_command(vm)

def parse_args():
    if len(sys.argv) != 2:
        print USAGE
        sys.exit(1)
    deployment = sys.argv[1]
    return deployment

if __name__ == "__main__":
    main()
